apiVersion: v1
kind: Pod
metadata:
  name: tempmicollabpod
spec:
  containers:
  - name: tempmicollabpod
    #image: gcr.io/integration-238016/micollab:9.0.0.2-04
    image: gcr.io/projects-jayant/micollab:9.0.0.2-04
    imagePullPolicy: Always
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - ALL
      privileged: true
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - name: micollab-data
      mountPath: /mnt
      subPath: mnt/
#    - name: micollab-data
#      mountPath: /var/lib/pgsql/10/data
#      subPath: mnt/db/
#    - name: micollab-data
#      mountPath: /home/e-smith/db
#      subPath: mnt/homeesmith/
#    - name: micollab-data
#      mountPath: /var/lib/ldap/
#      subPath: mnt/ldap/
#    - name: micollab-data
#      mountPath: /etc/e-smith/db
#      subPath: mnt/etc/
#    - name: micollab-data
#      mountPath: /var/log/awc
#      subPath: mnt/awclogs/
#    - name: micollab-data
#      mountPath: /var/log/e-smith
#      subPath: mnt/esmithlogs/
  volumes:
  - name: micollab-data
    persistentVolumeClaim: 
      claimName: micollab-pvc
---

